plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'io.github.garrettmac.duo'
version = '0.1.0-beta.0'

android {
  namespace "io.github.garrettmac.duo"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
}

dependencies {
  implementation "androidx.window:window:1.3.0"
}
